### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by Mrsevic** [Luffiez/RemoteDesktopViewer#1]
Hi.

Could you please insert installer in the release package?

Thanks

**Comment by Luffiez** [comment]
Hi!

The installer is included in the [Source Code](https://github.com/Luffiez/RemoteDesktopViewer/archive/refs/tags/Version_1.zip)
![image](https://user-images.githubusercontent.com/22912502/113148817-97ef6200-9232-11eb-9cc4-d6834dd3a669.png)

**Comment by Luffiez** [comment]
But I also included the installer as a [separate file](https://github.com/Luffiez/RemoteDesktopViewer/releases/download/Version_1/RemodeDesktopViewer_V1_Installer.zip)!

![image](https://user-images.githubusercontent.com/22912502/113149119-f4eb1800-9232-11eb-9770-b03f3a3f3b70.png)
